{"stats": {"errors": 0, "failures": 2, "passes": 8, "skipped": 0, "encoding": "UTF-8", "total": 10}, "results": [{"classname": "index_test:TestDictionary", "name": "test_area", "time": 0.00020766258239746094, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_change_spelling", "time": 0.00011038780212402344, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_count", "time": 7.677078247070312e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_keys", "time": 7.200241088867188e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_city_values", "time": 9.083747863769531e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_greenville_population", "time": 7.772445678710938e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_los_cabos_pop", "time": 0.0001952648162841797, "type": "failure", "errtype": "builtins.AssertionError", "message": "{'City': 'Los Cabos', 'Country': 'Mexico', 'Population': 287651, 'Area': 3750} != 287651", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/tkoar/python-dictionaries-lab-data-science-pilot/test/index_test.py\", line 21, in test_los_cabos_pop\n    self.assertEqual(los_cabos_pop, 287651)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 829, in _baseAssertEqual\n    raise self.failureException(msg)\nAssertionError: {'City': 'Los Cabos', 'Country': 'Mexico', 'Population': 287651, 'Area': 3750} != 287651\n"}, {"classname": "index_test:TestDictionary", "name": "test_pyeongchang_keys", "time": 9.965896606445312e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_pyeongchang_values", "time": 8.869171142578125e-05, "type": "success"}, {"classname": "index_test:TestDictionary", "name": "test_salina", "time": 0.00048613548278808594, "type": "failure", "errtype": "builtins.AssertionError", "message": "{'City': 'PyeongChang', 'Country': 'South K[38 chars]3194} != {'Area': 27, 'City': 'Salina Island', 'Coun[29 chars]4000}\n+ {'Area': 27, 'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000}\n- {'Area': 3194,\n-  'City': 'PyeongChang',\n-  'Country': 'South Korea',\n-  'Population': 2581000}", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 67, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 625, in run\n    testMethod()\n  File \"/home/tkoar/python-dictionaries-lab-data-science-pilot/test/index_test.py\", line 18, in test_salina\n    self.assertEqual(salina, {'Area': 27, 'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000})\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 836, in assertEqual\n    assertion_func(first, second, msg=msg)\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 1128, in assertDictEqual\n    self.fail(self._formatMessage(msg, standardMsg))\n  File \"/opt/conda/lib/python3.6/site-packages/unittest2/case.py\", line 690, in fail\n    raise self.failureException(msg)\nAssertionError: {'City': 'PyeongChang', 'Country': 'South K[38 chars]3194} != {'Area': 27, 'City': 'Salina Island', 'Coun[29 chars]4000}\n+ {'Area': 27, 'City': 'Salina Island', 'Country': 'Italy', 'Population': 4000}\n- {'Area': 3194,\n-  'City': 'PyeongChang',\n-  'Country': 'South Korea',\n-  'Population': 2581000}\n"}]}